In [2]:
import pandas as pd
import os

In [2]:
# CSV file called combined_data.csv
for filename in os.listdir('./CSV Data'):
    print(filename)
    for file in os.listdir(f'./CSV Data/{filename}'):
        if file.endswith('.csv'):
            df = pd.read_csv(f'./CSV Data/{filename}/{file}')
            new_df = df[['Issue Type', 'Status', 'Priority', 'Summary', 'Original Time Estimated', 'Total Time Spent']].copy()
            new_df = new_df[:-1]
            new_df['Summary'] = new_df['Summary'].str.replace(r'WS-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'PALM-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'APO-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'MED-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'[^\w\s]', '', regex=True)
            new_df['Issue Type'] = new_df['Issue Type'].str.replace(r'[^\w\s]', '', regex=True)
            # add header if the file doesn't exist yet
            if not os.path.isfile('./Cleaned Data/combined_data.csv'):
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=True, index=False)
            else:
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=False, index=False)

weos data
med AI
Apollo
Marritime
PALM

In [3]:
# load cleaned data into a dataframe
project_df = pd.read_csv('./Cleaned Data/combined_data.csv')

In [4]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
0,Bug,Done,Blocker,When an integration has the option to setup su...,-,30m
1,Bug,Done,Major,Getting a null error response when first loadi...,-,1h 5m
2,Story,Done,Critical,I should be able to setup a Finance assistant,-,0m
3,Task,Done,Major,UI Cleanup,-,-
4,Story,Done,Critical,When my session expires I should be taken to l...,1h,1h
...,...,...,...,...,...,...
1880,Subtask,Done,Major,setup account domain object and gorm model,-,-
1881,Subtask,Done,Major,Add screen for editing a bill,-,-
1882,Subtask,Done,Major,add screen for listing schedules,-,-
1883,Subtask,Done,Major,Add view screen for categorie that shows items,-,-
1884,Subtask,Done,Major,remove previous email that was being sent,-,-

In [7]:
# remove all the records with the total timespent is empty ie '-'
project_df = project_df[project_df['Total Time Spent'] != '-']

In [10]:
# remove all the records with the original time estimated is empty ie '-'
project_df = project_df[project_df['Original Time Estimated'] != '-']

In [11]:
project_df.describe()

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
count,865,865,857,865,865,865
unique,6,8,4,848,26,232
top,Subtask,Done,Major,Feedback,1h,1h
freq,649,817,807,9,346,150

In [12]:
# Store the cleaned data into a new CSV file
project_df.to_csv('./Cleaned Data/cleaned_data.csv', index=False)