In [16]:
import pandas as pd
import os

In [17]:
# CSV file called combined_data.csv
for filename in os.listdir('./CSV Data'):
    print(filename)
    for file in os.listdir(f'./CSV Data/{filename}'):
        if file.endswith('.csv'):
            df = pd.read_csv(f'./CSV Data/{filename}/{file}')
            new_df = df[['Issue Type', 'Status', 'Priority', 'Summary', 'Original Time Estimated', 'Total Time Spent']].copy()
            new_df = new_df[:-1]
            new_df['Summary'] = new_df['Summary'].str.replace(r'WS-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'PALM-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'APO-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'MED-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'[^\w\s]', '', regex=True)
            new_df['Issue Type'] = new_df['Issue Type'].str.replace(r'[^\w\s]', '', regex=True)
            # add header if the file doesn't exist yet
            if not os.path.isfile('./Cleaned Data/combined_data.csv'):
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=True, index=False)
            else:
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=False, index=False)

weos data
med AI
Apollo
Marritime
PALM

In [18]:
# load cleaned data into a dataframe
project_df = pd.read_csv('./Cleaned Data/combined_data.csv')

In [19]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
0,Bug,Done,Blocker,When an integration has the option to setup su...,-,30m
1,Bug,Done,Major,Getting a null error response when first loadi...,-,1h 5m
2,Story,Done,Critical,I should be able to setup a Finance assistant,-,0m
3,Task,Done,Major,UI Cleanup,-,-
4,Story,Done,Critical,When my session expires I should be taken to l...,1h,1h
...,...,...,...,...,...,...
1880,Subtask,Done,Major,setup account domain object and gorm model,-,-
1881,Subtask,Done,Major,Add screen for editing a bill,-,-
1882,Subtask,Done,Major,add screen for listing schedules,-,-
1883,Subtask,Done,Major,Add view screen for categorie that shows items,-,-
1884,Subtask,Done,Major,remove previous email that was being sent,-,-

In [20]:
# remove all the records with the total timespent is empty ie '-'
project_df = project_df[project_df['Total Time Spent'] != '-']

In [21]:
# remove all the records with the original time estimated is empty ie '-'
project_df = project_df[project_df['Original Time Estimated'] != '-']

In [22]:
project_df.describe()

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
count,865,865,857,865,865,865
unique,6,8,4,848,26,232
top,Subtask,Done,Major,Feedback,1h,1h
freq,649,817,807,9,346,150

In [23]:
def to_minutes(time_str: str, hours_per_day: int = 8) -> int:
    total_minutes = 0

    # Split the input string by spaces
    parts = time_str.split()

    for part in parts:
        if part.endswith('d'):
            num = float(part[:-1])
            total_minutes += num * hours_per_day * 60
        elif part.endswith('h'):
            num = float(part[:-1])
            total_minutes += num * 60
        elif part.endswith('m'):
            num = float(part[:-1])
            total_minutes += num

    return int(total_minutes)

In [24]:
project_df['Total Time Spent'] = project_df['Total Time Spent'].apply(to_minutes)

In [25]:
project_df['Original Time Estimated'] = project_df['Original Time Estimated'].apply(to_minutes)

In [26]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
4,Story,Done,Critical,When my session expires I should be taken to l...,60,60
7,Task,Done,Major,Update the payment config to only have mapping...,30,30
8,Bug,Done,Critical,The wrong date is showing up on payouts and or...,30,38
9,Task,Done,Major,Rename Sparks and Signals,30,30
36,Task,QA,Critical,Create basic WeOS Slack App,0,240
...,...,...,...,...,...,...
1870,Subtask,Done,Major,Add a form for creating a vendor item,120,60
1871,Subtask,Done,Major,Add command receiver and endpoint for creati...,120,60
1872,Subtask,In Progress,Major,Update the expense form to show list of rela...,120,390
1873,Subtask,Done,Major,Add form for editing invoice,120,40
1875,Subtask,Done,Major,Hook up editing vendor quote screen,60,60

In [27]:
# Store the cleaned data into a new CSV file
project_df.to_csv('./Cleaned Data/cleaned_data.csv', index=False)